"""Shared AdMapix API client."""

from __future__ import annotations

from typing import Literal

import httpx


SearchSchema = Literal["raw", "normalized"]


async def call_admapix_search(
    params: dict,
    api_key: str,
    base_url: str = "https://api.admapix.com",
    timeout: int = 30,
    schema: SearchSchema = "raw",
) -> dict:
    """Call AdMapix search API.

    The default ``raw`` schema returns upstream data fields directly, with the
    request body attached for reproducibility. No presentation payload is
    generated by this client.
    """
    if not api_key:
        return _error(
            "missing_api_key",
            "Missing ADMAPIX_API_KEY environment variable",
        )

    body = build_search_body(params)
    headers = {"X-API-Key": api_key, "Content-Type": "application/json"}

    try:
        async with httpx.AsyncClient(timeout=timeout) as http:
            response = await http.post(
                f"{base_url}/api/data/search",
                json=body,
                headers=headers,
            )
    except httpx.TimeoutException:
        return _error("timeout", "Request timed out", retry=True)
    except Exception as exc:
        return _error("request_failed", f"Request failed: {exc}")

    if response.status_code == 401:
        return _error("auth_failed", "Authentication failed: invalid API key")
    if response.status_code == 403:
        return _error("forbidden", "Access forbidden")
    if response.status_code == 429:
        return _error("rate_limited", "Rate limited; try again later", retry=True)

    try:
        data = response.json()
    except ValueError:
        return _error("invalid_response", "AdMapix returned a non-JSON response")

    if isinstance(data.get("detail"), str):
        msg = data["detail"]
        code = "quota_exhausted" if "quota" in msg.lower() else "api_error"
        return _error(code, msg)

    if schema == "normalized":
        return normalize_creative_response(data, body)

    result = dict(data)
    result["request"] = body
    result["page"] = body["page"]
    result["page_size"] = body["page_size"]
    result.setdefault("list", [])
    return result


def build_search_body(params: dict) -> dict:
    """Build the flat AdMapix search request body."""
    body: dict = {
        "content_type": "creative",
        "keyword": params.get("keyword", ""),
        "page": max(int(params.get("page") or 1), 1),
        "page_size": min(max(int(params.get("page_size") or 20), 1), 60),
        "sort_field": params.get("sort_field", "3"),
        "sort_rule": params.get("sort_rule", "desc"),
    }
    for key in ("start_date", "end_date", "country_ids", "creative_team", "trade_level1"):
        if params.get(key):
            body[key] = params[key]
    return body


def normalize_creative_response(data: dict, request: dict) -> dict:
    """Return a compact normalized schema for callers that need stable keys."""
    items = []
    for raw in data.get("list") or []:
        items.append(
            {
                "id": raw.get("id"),
                "title": raw.get("title"),
                "describe": raw.get("describe"),
                "image_urls": raw.get("imageUrl") or [],
                "video_urls": raw.get("videoUrl") or [],
                "playable_urls": raw.get("playHtmlUrl") or [],
                "first_seen": raw.get("globalFirstTime") or raw.get("firstTime"),
                "last_seen": raw.get("globalLastTime") or raw.get("lastTime"),
                "days_found": raw.get("findCntSum") or raw.get("findCnt"),
                "impression": raw.get("impression"),
                "show_count": raw.get("showCnt") or raw.get("demoadCnt"),
                "ad_source": raw.get("adSource"),
                "apps": [
                    {"name": app.get("name"), "pkg": app.get("pkg"), "logo": app.get("logo")}
                    for app in (raw.get("appList") or [])
                ],
                "website": raw.get("webSite") or raw.get("demoadWebSite"),
            }
        )

    return {
        "request": request,
        "total": data.get("totalSize"),
        "page": request["page"],
        "page_size": request["page_size"],
        "items": items,
    }


def _error(code: str, message: str, retry: bool = False) -> dict:
    return {"error": {"code": code, "message": message, "retry": retry}}
